### ISSUE TITLE
Device Not Supported

### ISSUE THREAD

**Issue by jcodesss** [ErrorErrorError/SSKeyboardHue#3]
[GE62VR ](https://www.msi.com/Laptop/GE62VR-6RF-Apache-Pro/Specification)have Steelseries3. Would you make for it

**Comment by erikbdev** [comment]
What kind of keyboard is it? Is it Three region key or can you change the lights on each individual keys?

**Comment by jcodesss** [comment]
three region key.

**Comment by erikbdev** [comment]
> three region key.

Those are the plans to bring support for three region key, however there seems to be an issue with the USB keyboard on macOS. Do you receive any errors about MSI USB EPF or something like that?

**Comment by jcodesss** [comment]
No.

**Comment by erikbdev** [comment]
Can you upload your System Report on USB? You can get it on the top left apple logo, About this mac..., clicking System Report and then clicking USB and take a screenshot of the MSI EPF.

**Comment by jcodesss** [comment]
MSI EPF Not Found.

**Comment by erikbdev** [comment]
> MSI EPF Not Found.

You must have it disabled in your USB config. It will need to be enabled in order to actually send commands for the LED. I will add support on a future release, but right now I need to clean up code.

**Comment by jcodesss** [comment]
<img width="622" alt="Screen Shot 2020-05-13 at 5 39 06 PM" src="https://user-images.githubusercontent.com/63956583/81796920-a8c2b680-9540-11ea-98bd-ff113cf390d0.png">
How to enable EPF?
